knp_paginator:
    page_range: 5                       # Número de páginas que se muestran en el paginador
    default_options:
        page_name: page                 # Nombre del parámetro de página en la URL
        sort_field_name: sort           # Nombre del parámetro de ordenamiento en la URL
        sort_direction_name: direction  # Nombre del parámetro de dirección de ordenamiento en la URL
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
